sanitized AR/lib.exe call. removing bogus arg @printf from the list for MSYS2 + MSVC env

diff --git a/compat/windows/makedef b/compat/windows/makedef
--- a/compat/windows/makedef
+++ b/compat/windows/makedef
@@ -45,14 +45,29 @@ libname=$(mktemp -u "library").lib
 
 trap 'rm -f -- $libname' EXIT
 
+#if [ -n "$AR" ]; then
+#    $AR rcs ${libname} $@ >/dev/null
+#else
+#    lib.exe -out:${libname} $@ >/dev/null
+#fi
+#if [ $? != 0 ]; then
+#    echo "Could not create temporary library." >&2
+#    exit 1
+#fi
+
+# --- sanitized AR/lib.exe call ---
+args=""
+for arg in "$@"; do
+    case "$arg" in
+        @printf) ;;  # skip bogus arg
+        *) args="$args \"$arg\"" ;;
+    esac
+done
+
 if [ -n "$AR" ]; then
-    $AR rcs ${libname} $@ >/dev/null
+    eval $AR rcs "${libname}" $args >/dev/null
 else
-    lib.exe -out:${libname} $@ >/dev/null
-fi
-if [ $? != 0 ]; then
-    echo "Could not create temporary library." >&2
-    exit 1
+    eval lib.exe -out:"${libname}" $args >/dev/null
 fi
 
 IFS='
